### ISSUE TITLE
Flexbox and scrolling

### ISSUE THREAD

**Issue by dnish** [rommguy/react-custom-scroll#11]
Hey,
just fixed some div's of the other issue, now I'm trying to add custom scroll to a flexbox layout. For example, we are having the following structure:

    <div id="chat">
      <div class="header"></div>
      <div class="messages"><CustomScroll heightRelativeToParent="100%">....</CustomScroll></div>
       <div class="write"></div>
    </div>

CSS:

    #chat {
     display: flex;
     flex-direction:column;
    }

    .header {
      height: 60px;
     }

    .messages {
      flex: 1;
      overflow-y:hidden;
    }

    .writer {
     height: 50px;
     }

If I start scrolling, I've 2 scrollbars within my messages div. The one of CustomScroll and the native one. I think that overflow-y causes the issue, but it's needed because of <code>flex:1;</code>. Any idea how I could fix this issue?

**Comment by rommguy** [comment]
Hey,
I'll check, It would take me a few days

**Comment by rommguy** [comment]
Hi @dnish ,
I played a little with the code you wrote, and it works o for me, even with the overflow-y: hidden on the messages element.
Just to make sure - the '#chat' element has some kind of height limit like max-height right ?

**Comment by dnish** [comment]
Hey @rommguy,
thank you for your answer. You can check our layout [here](https://www.elternsachen.de). We have the double scrollbars on all 3 content elements. At the moment I've fixed the issue with a CSS code that hides all native scrollbars on Webkit.

**Comment by rommguy** [comment]
I opened your link in FireFox and I still see only the custom scrollbar. Maybe it is an OS issue - are you using windows ? which version ?

**Comment by dnish** [comment]
It only happens Mac + Chrome - I've removed the CSS fix from our site, now you should also see 2 scrollbars.

**Comment by rommguy** [comment]
I cleaned cache and refreshed, but can't see the bug.
Here is a [screen capture from FireFox](http://screencast.com/t/3UAWJvY4tx)
And here is a [screen capture from Chrome](http://screencast.com/t/iuAEayqg)

Can you check the margin-right calculated value on inner-container ?

**Comment by dnish** [comment]
It is 20px - I see that the background of the third box covers the second scrollbar. Are you able to set <code>#start_page { display:'none'; } </code> within your browser? Then you should also see the second scrollbar on the topic list.

**Comment by rommguy** [comment]
@dnish I finally found the issue!!
It turns out flex does not allow the content to shrink, unless you explicitly use min-height: 0, min-width: 0
I'll push a fix as soon as possible and update

**Comment by rommguy** [comment]
@dnish Please take a look at the updated Readme file. 
I've added explanations on how to use with flex. The problem you saw can be fixed by setting min-width : 0.
You can also see the example in the demo page.
I'll update the npm package tomorrow with the support for flex property
